version: '3'
services:
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ".:/myapp"
      - bundle:/myapp/vendor/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  bundle:
