FROM node:12.18.3-alpine
RUN apk update && \
    apk add git && \
    npm install -g npm && \
    npm install -g vue-cli
RUN mkdir /myfront
COPY ./kakeibo-front /myfront
WORKDIR /myfront
RUN npm install
