version: '3'
services:
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ".:/myapp"
      - bundle:/myapp/vendor/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true
  front:
    build:
      context: .
      dockerfile: Dockerfile-front
    working_dir: /myfront
    command: npm run dev
    environment:
      HOST: 0.0.0.0
    ports:
      - "8080:3000"
    volumes:
      - "./kakeibo-front:/myfront"
      - node_modules:/myfront/node_modules
volumes:
  bundle:
  node_modules:
